# Generated by Django 4.2.8 on 2023-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notes_options_alter_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='api/media/'),
        ),
    ]
