# Generated by Django 4.2.8 on 2023-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notes_desc_alter_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
