# Generated by Django 4.2.8 on 2023-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notes_title_alter_notes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
